### ISSUE TITLE
Fix Composer 2 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [24hoursmedia-craftcms/views-work#1]
When installing this plugin with Composer 1, the following deprecation notice is output:

> Deprecation Notice: Class `twentyfourhoursmedia\viewswork\assetbundles\ViewsWork\ViewsWorkAsset` located in `./vendor/twentyfourhoursmedia/views-work/src/assetbundles/viewswork/ViewsWorkAsset.php` does not comply with psr-4 autoloading standard\. It will not autoload anymore in Composer v2\.0\.

Composer 2 was released on October 24, and is now the default version that will be installed, so it’s critical that this gets resolved ASAP, or people will start getting `Class not found` errors.

To fix, run the following command:

```bash
> git mv src/assetbundles/viewswork src/assetbundles/ViewsWork
```

Then commit your change and [tag a new release](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases).

_(Note that you must use the `git mv` command, as Git tends to not notice case-sensitive file renames otherwise.)_

**Comment by 24HOURSMEDIA** [comment]
@brandonkelly thanks so much.
It turned out to be more complex on Mac osx to make this simple change.

I had to change .git/config according to https://www.garron.me/en/bits/git-ignorecase-rename-lowercase-uppercase.html
but in the end I ended up in renaming the directory, commit, then rename again to uppercased version and commit.
