### ISSUE TITLE
Block users based on user group

### ISSUE THREAD

**Issue by zizther** [24hoursmedia-craftcms/views-work#54]
It would be great to have a config setting where you could block users who are associated to a certain group so that they would not log any content views, this could work alongside the cookie implementation still.
It would provide a better way, out the box, to reduce false views across multiple browsers and devices.

**Comment by 24hoursmedia-craftcms** [comment]
Hi @zizther 

There could be so many different reasons to block logging a view, and custom for each site/deployment.

That's why you can write your own mechanism/criteria quite easily with an event listener in a module, so you can customize logging to your own needs (based on user agent, ip, logged in status, user group, a 'switch' in the user account etc etc).

An example can be found at
https://io.24hoursmedia.com/views-work/events

**Comment by zizther** [comment]
@24hoursmedia-craftcms Great stuff, this would be really handy, thanks for building in the extensibility
